#server:
#  port: 8085
#spring:
#  application:
#    name: api-gateway-service
##  cloud:
##    gateway:
##      routes:
##        - id: order-service
##          uri: lb://ORDER-SERVICE
##          predicates:
##            - Path=/ORDER_SERVICE/api/orders/**
##        - id: product-service
##          uri: lb://PRODUCT-SERVICE
##          predicates:
##            - Path=/PRODUCT_SERVICE/api/products/**
##        - id: user-service
##          uri: lb://USER-SERVICE
##          predicates:
##            - Path=/USER_SERVICE/api/users/**
#    discovery:
#      locator:
#        enabled: true
#      discovery:
#        client:
#          service-url:
#            defaultZone: http://localhost:8761/
#
##  management:
##    endpoints:
##      web:
##        exposure:
##          include: **
##  main:
##    web-application-type: reactive
##
