spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order_service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  cloud:
    discovery:
      client:
        service-url:
        defaultZone: http://localhost:8761/
  rabbitmq:
    virtualHost: wwwbjske
    host: dog-01.lmq.cloudamqp.com
    username: wwwbjske
    password: YB-I9mXxL-wmvDZ7EaxYJb4yuNj630Zk
    port: 5672
server:
  port: 8081








