spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/usersdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  cloud:
    discovery:
      client:
        service-url:
        defaultZone: http://localhost:8761/
server:
  port: 8083

rsa:
  private-key: classpath:certs/private-keyy.pem
  public-key: classpath:certs/public-key.pem









